apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: hello-temporalio
build:
  artifacts:
    - image: hello-temporalio-app-worker
      context: app
      docker:
        dockerfile: app/Dockerfile
        buildArgs:
          TARGET: "worker"
    - image: hello-temporalio-app-workflow
      context: app
      docker:
        dockerfile: app/Dockerfile
        buildArgs:
          TARGET: "workflow"
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
      # app
      - k8s/app/worker/*.yaml
      - k8s/app/workflow/*.yaml
      # temporal
      - k8s/temporal/admintools/*.yaml
      - k8s/temporal/cassandra/*.yaml
      - k8s/temporal/server/*.yaml
      - k8s/temporal/web/*.yaml
portForward:
  - resourceType: service
    resourceName: hello-temporalio-app-worker
    namespace: app
    port: 9000
    localPort: 9000
  - resourceType: service
    resourceName: hello-temporalio-app-workflow
    namespace: app
    port: 9001
    localPort: 9001
  - resourceType: service
    resourceName: hello-temporalio-temporal-web
    namespace: temporal
    port: 8088
    localPort: 8088
