apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-temporalio-app-workflow
  namespace: app
  labels:
    app: hello-temporalio-app-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-temporalio-app-workflow
  template:
    metadata:
      labels:
        app: hello-temporalio-app-workflow
    spec:
      containers:
        - name: hello-temporalio-app-workflow
          image: hello-temporalio-app-workflow:latest
          env:
            - name: PORT
              value: "9001"
            - name: TEMPORAL_GRPC_ENDPOINT
              value: "hello-temporalio-temporal-frontend.temporal.svc:7233"
