apiVersion: v1
kind: Service
metadata:
  name: hello-temporalio-app-workflow
  namespace: app
  labels:
    app: hello-temporalio-app-workflow
spec:
  type: LoadBalancer
  selector:
    app: hello-temporalio-app-workflow
  ports:
    - port: 9001
