apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-temporalio-app-api
  namespace: app
  labels:
    app: hello-temporalio-app-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-temporalio-app-api
  template:
    metadata:
      labels:
        app: hello-temporalio-app-api
    spec:
      containers:
        - name: hello-temporalio-app-api
          image: hello-temporalio-app-api:latest
