apiVersion: batch/v1
kind: Job
metadata:
  name: hello-temporalio-temporal-schema-setup
  namespace: temporal
  labels:
    app: database
spec:
  backoffLimit: 100
  template:
    metadata:
      name: hello-temporalio-temporal-schema-setup
      labels:
        app: database
    spec:
      restartPolicy: "OnFailure"
      initContainers:
        - name: check-cassandra-service
          image: busybox
          command: ['sh', '-c', 'until nslookup hello-temporalio-temporal-cassandra.temporal.svc.cluster.local; do echo waiting for cassandra service ...; sleep 1; done;']
        - name: check-cassandra
          image: "cassandra:3.11.3"
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until cqlsh hello-temporalio-temporal-cassandra.temporal.svc.cluster.local 9042 -e "SHOW VERSION"; do echo waiting for cassandra to start up ...; sleep 1; done;']
        - name: create-default-store
          image: "temporalio/admin-tools:1.16.2"
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'temporal-cassandra-tool create -k temporal --replication-factor 1']
          env:
            - name: CASSANDRA_HOST
              value: hello-temporalio-temporal-cassandra.temporal.svc.cluster.local
            - name: CASSANDRA_PORT
              value: "9042"
            - name: CASSANDRA_KEYSPACE
              value: temporal
            - name: CASSANDRA_USER
              value: user
            - name: CASSANDRA_PASSWORD
              value: password
        - name: create-visibility-store
          image: "temporalio/admin-tools:1.16.2"
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'temporal-cassandra-tool create -k temporal_visibility --replication-factor 1']
          env:
            - name: CASSANDRA_HOST
              value: hello-temporalio-temporal-cassandra.temporal.svc.cluster.local
            - name: CASSANDRA_PORT
              value: "9042"
            - name: CASSANDRA_KEYSPACE
              value: temporal_visibility
            - name: CASSANDRA_USER
              value: user
            - name: CASSANDRA_PASSWORD
              value: password
      containers:
        - name: default-schema
          image: "temporalio/admin-tools:1.16.2"
          imagePullPolicy: IfNotPresent
          command: ["temporal-cassandra-tool", "setup-schema", "-v", "0.0"]
          env:
            - name: CASSANDRA_HOST
              value: hello-temporalio-temporal-cassandra.temporal.svc.cluster.local
            - name: CASSANDRA_PORT
              value: "9042"
            - name: CASSANDRA_KEYSPACE
              value: temporal
            - name: CASSANDRA_USER
              value: user
            - name: CASSANDRA_PASSWORD
              value: password
        - name: visibility-schema
          image: "temporalio/admin-tools:1.16.2"
          imagePullPolicy: IfNotPresent
          command: ["temporal-cassandra-tool", "setup-schema", "-v", "0.0"]
          env:
            - name: CASSANDRA_HOST
              value: hello-temporalio-temporal-cassandra.temporal.svc.cluster.local
            - name: CASSANDRA_PORT
              value: "9042"
            - name: CASSANDRA_KEYSPACE
              value: temporal_visibility
            - name: CASSANDRA_USER
              value: user
            - name: CASSANDRA_PASSWORD
              value: password
---
apiVersion: batch/v1
kind: Job
metadata:
  name: hello-temporalio-temporal-schema-update
  namespace: temporal
  labels:
    app: database
spec:
  backoffLimit: 100
  template:
    metadata:
      name: hello-temporalio-temporal-schema-update
      labels:
        app: database
    spec:
      restartPolicy: "OnFailure"
      initContainers:
        - name: check-cassandra-service
          image: busybox
          command: ['sh', '-c', 'until nslookup hello-temporalio-temporal-cassandra.temporal.svc.cluster.local; do echo waiting for cassandra service ...; sleep 1; done;']
        - name: check-cassandra
          image: "cassandra:3.11.3"
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until cqlsh hello-temporalio-temporal-cassandra.temporal.svc.cluster.local 9042 -e "SHOW VERSION"; do echo waiting for cassandra to start up ...; sleep 1; done;']
      containers:
        - name: default-schema
          image: "temporalio/admin-tools:1.16.2"
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'temporal-cassandra-tool update-schema -d /etc/temporal/schema/cassandra/temporal/versioned']
          env:
            - name: CASSANDRA_HOST
              value: hello-temporalio-temporal-cassandra.temporal.svc.cluster.local
            - name: CASSANDRA_PORT
              value: "9042"
            - name: CASSANDRA_KEYSPACE
              value: temporal
            - name: CASSANDRA_USER
              value: user
            - name: CASSANDRA_PASSWORD
              value: password
        - name: visibility-schema
          image: "temporalio/admin-tools:1.16.2"
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'temporal-cassandra-tool update-schema -d /etc/temporal/schema/cassandra/visibility/versioned']
          env:
            - name: CASSANDRA_HOST
              value: hello-temporalio-temporal-cassandra.temporal.svc.cluster.local
            - name: CASSANDRA_PORT
              value: "9042"
            - name: CASSANDRA_KEYSPACE
              value: temporal_visibility
            - name: CASSANDRA_USER
              value: user
            - name: CASSANDRA_PASSWORD
              value: password
