apiVersion: v1
kind: Secret
metadata:
  name: hello-temporalio-temporal-default-store
  namespace: temporal
type: Opaque
data:
  password: "UGEkJHcwcmQ="
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-temporalio-temporal-visibility-store
  namespace: temporal
type: Opaque
data:
  password: "UGEkJHcwcmQ="
