apiVersion: v1
kind: Service
metadata:
  name: hello-temporalio-temporal-frontend
  namespace: temporal
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 7233
      targetPort: rpc
      protocol: TCP
      name: grpc-rpc
---
apiVersion: v1
kind: Service
metadata:
  name: hello-temporalio-temporal-matching
  namespace: temporal
  labels:
    app: matching
spec:
  type: ClusterIP
  selector:
    app: matching
  ports:
    - port: 7235
      targetPort: rpc
      protocol: TCP
      name: grpc-rpc
---
apiVersion: v1
kind: Service
metadata:
  name: hello-temporalio-temporal-history
  namespace: temporal
  labels:
    app: history
spec:
  type: ClusterIP
  selector:
    app: history
  ports:
    - port: 7234
      targetPort: rpc
      protocol: TCP
      name: grpc-rpc
---
apiVersion: v1
kind: Service
metadata:
  name: hello-temporalio-temporal-worker
  namespace: temporal
  labels:
    app: worker
spec:
  type: ClusterIP
  selector:
    app: worker
  ports:
    - port: 7239
      targetPort: rpc
      protocol: TCP
      name: grpc-rpc
