apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-temporalio-app-worker
  namespace: app
  labels:
    app: hello-temporalio-app-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-temporalio-app-worker
  template:
    metadata:
      labels:
        app: hello-temporalio-app-worker
    spec:
      containers:
        - name: hello-temporalio-app-worker
          image: hello-temporalio-app-worker:latest
