apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-temporalio-temporal-web
  namespace: temporal
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: temporal-web
          image: "temporalio/web:1.15.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: TEMPORAL_GRPC_ENDPOINT
              value: "hello-temporalio-temporal-frontend.temporal.svc:7233"
          volumeMounts:
            - name: temporal-web-config
              mountPath: /usr/app/server/config.yml
              subPath: config.yml
          ports:
            - name: http
              containerPort: 8088
              protocol: TCP
      volumes:
        - name: temporal-web-config
          configMap:
            name: hello-temporalio-temporal-web-config
