apiVersion: v1
kind: Service
metadata:
  name: hello-temporalio-temporal-web
  namespace: temporal
  labels:
    app: web
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - port: 8088
      targetPort: http
      protocol: TCP
      name: http
